backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: "/images"
publish_mode: editorial_workflow

collections:
- label: "Pages"
  name: "pages"
  files:
  - label: "Home Page"
    name: "home"
    file: "_content/home.json"
    fields:
    - label: "SEO"
      name: "seo"
      widget: "object"
      fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: string}
    - {label: Title, name: title, widget: string}
  - label: "About Page"
    name: "about"
    file: "_content/about.json"
    fields:
    - label: "SEO"
      name: "seo"
      widget: "object"
      fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: string}
    - {label: Title, name: title, widget: string}
  - label: "Contact Page"
    name: "contact"
    file: "_content/contact.json"
    fields:
    - label: "SEO"
      name: "seo"
      widget: "object"
      fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: string}
    - {label: Title, name: title, widget: string}
    - label: "Form"
      name: "form"
      widget: "object"
      fields:
      - {label: Name, name: name, widget: string}
      - {label: Email, name: email, widget: string}
      - {label: Message, name: message, widget: string}
      - {label: Submit, name: submit, widget: string}
