backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: "/images"
publish_mode: editorial_workflow

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        format: "json",
        file: "index.json"
        fields:
          - label: 'SEO'
            name: 'seo'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
          - { label: Title, name: title, widget: string }
      - label: "About Page"
        name: "about"
        file: "about/about.json"
        fields:
          - label: 'SEO'
            name: 'seo'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
          - { label: Title, name: title, widget: string }